name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kantaponh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: ðŸ›  Build and tag Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: ðŸš€ Tag & Push Backend image
        run: |
          docker tag todo101-todo-backend kantaponh/todo-backend:latest
          docker push kantaponh/todo-backend:latest

      - name: ðŸš€ Tag & Push Frontend image
        run: |
          docker tag todo101-todo-frontend kantaponh/todo-frontend:latest
          docker push kantaponh/todo-frontend:latest
